### PR TITLE
uses environment variable to specify load test host

### PR DESCRIPTION
**Pull request by kyleburnsdev**
I haven't been able to get the CI/CD working on my fork, so this needs to be tested before integration. Reference used was https://docs.microsoft.com/en-us/azure/load-testing/how-to-parameterize-load-tests

### CODE REVIEW

**Review by RPagels — APPROVED** [review]
Refactored for Load Testing Parms

**Comment by RPagels** [comment]
Refactored for Load Testing Parms

**Comment by kyleburnsdev** [comment]
Resolved merge conflicts

**Comment by RPagels** [comment]
Accepted Load Test Parms

**Pull request merged**
